comment: false
coverage:
  status:
    project:
      default:
        informational: true
    patch: off

ignore:
  - "**/test_*.py"
  - "selfdrive/test/**"
  - "system/version.py" # codecov changes depending on if we are in a branch or not
  - "tools"
