FROM ghcr.io/sunnypilot/sunnypilot-base:latest

ENV PYTHONUNBUFFERED=1

ENV OPENPILOT_PATH=/home/batman/openpilot

RUN mkdir -p ${OPENPILOT_PATH}
WORKDIR ${OPENPILOT_PATH}

COPY . ${OPENPILOT_PATH}/

RUN scons --cache-readonly -j$(nproc)
