from openpilot.common.realtime import DT_MDL


class WMACConstants:
  TRAJECTORY_SIZE = 33
  PARAM_READ_FRAMES = max(1, int(round(1.0 / DT_MDL)))

  EMERGENCY_HOLD_FRAMES = max(1, int(round(0.75 / DT_MDL)))
  MIN_MODE_DURATION = {'acc': max(1, int(round(0.6 / DT_MDL))), 'blended': max(1, int(round(0.5 / DT_MDL)))}
  ENTER_BLENDED_FRAMES = max(1, int(round(0.4 / DT_MDL)))
  EXIT_BLENDED_FRAMES = max(1, int(round(0.35 / DT_MDL)))
  STANDSTILL_FRAMES = max(1, int(round(0.2 / DT_MDL)))

  LEAD_PROB = 0.45
  LEAD_EXIT_PROB = 0.25
  LEAD_RISE_RATE = 1.0
  LEAD_FALL_RATE = 0.35
  RADAR_LEAD_CONTINUITY_FRAMES = max(1, int(round(1.0 / DT_MDL)))
  RADAR_LEAD_DROPOUT_FRAMES = max(1, int(round(0.2 / DT_MDL)))
  RADAR_STALE_FRAMES = max(1, int(round(0.5 / DT_MDL)))

  SLOW_DOWN_PROB = 0.5
  SLOW_DOWN_EXIT_PROB = 0.4
  SLOW_DOWN_RISE_RATE = 0.65
  SLOW_DOWN_FALL_RATE = 0.15
  SLOW_DOWN_BP = [0., 10., 20., 30., 40., 50., 55., 60.]
  SLOW_DOWN_DIST = [32., 46., 64., 86., 108., 130., 145., 165.]
  URGENT_SLOW_DOWN_PROB = 0.85

  MODEL_DECEL_START = -0.5
  MODEL_DECEL_RANGE = 2.0
  MODEL_DECEL_TREND_FRAMES = 4
  MODEL_DECEL_TREND_ACCEL = -0.075
  MODEL_DECEL_TREND_RATE = 0.35
  MODEL_DECEL_TREND_MAX_MPC_ACCEL = 0.075
  MODEL_DECEL_TREND_MAX_COMMAND_STEP = 0.15
  MODEL_DECEL_TREND_RELEASE_ACCEL = -0.02
  ENDPOINT_URGENCY_GAIN = 1.3
  CRITICAL_ENDPOINT_FACTOR = 0.3
  CRITICAL_URGENCY_GAIN = 1.5
  SPEED_URGENCY_MIN = 25.0
  SPEED_URGENCY_RANGE = 80.0

  SLOWNESS_PROB = 0.55
  SLOWNESS_EXIT_PROB = 0.45
  SLOWNESS_RISE_RATE = 0.35
  SLOWNESS_FALL_RATE = 0.5
  SLOWNESS_CRUISE_OFFSET = 1.025
