#pragma once

#include <string>
#include <unordered_map>

inline static std::unordered_map<std::string, uint32_t> keys = {
    {"AccessToken", CLEAR_ON_MANAGER_START | DONT_LOG},
    {"AdbEnabled", PERSISTENT | BACKUP},
    {"AlwaysOnDM", PERSISTENT | BACKUP},
    {"ApiCache_Device", PERSISTENT},
    {"ApiCache_FirehoseStats", PERSISTENT},
    {"AssistNowToken", PERSISTENT},
    {"AthenadPid", PERSISTENT},
    {"AthenadUploadQueue", PERSISTENT},
    {"AthenadRecentlyViewedRoutes", PERSISTENT},
    {"BootCount", PERSISTENT},
    {"CalibrationParams", PERSISTENT},
    {"CameraDebugExpGain", CLEAR_ON_MANAGER_START},
    {"CameraDebugExpTime", CLEAR_ON_MANAGER_START},
    {"CarBatteryCapacity", PERSISTENT},
    {"CarParams", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"CarParamsCache", CLEAR_ON_MANAGER_START},
    {"CarParamsPersistent", PERSISTENT},
    {"CarParamsPrevRoute", PERSISTENT},
    {"CompletedTrainingVersion", PERSISTENT},
    {"ControlsReady", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"CurrentBootlog", PERSISTENT},
    {"CurrentRoute", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"DisableLogging", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"DisablePowerDown", PERSISTENT | BACKUP},
    {"DisableUpdates", PERSISTENT | BACKUP},
    {"DisengageOnAccelerator", PERSISTENT | BACKUP},
    {"DongleId", PERSISTENT},
    {"DoReboot", CLEAR_ON_MANAGER_START},
    {"DoShutdown", CLEAR_ON_MANAGER_START},
    {"DoUninstall", CLEAR_ON_MANAGER_START},
    {"AlphaLongitudinalEnabled", PERSISTENT | DEVELOPMENT_ONLY | BACKUP},
    {"ExperimentalMode", PERSISTENT | BACKUP},
    {"ExperimentalModeConfirmed", PERSISTENT | BACKUP},
    {"FirmwareQueryDone", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"ForcePowerDown", PERSISTENT},
    {"GitBranch", PERSISTENT},
    {"GitCommit", PERSISTENT},
    {"GitCommitDate", PERSISTENT},
    {"GitDiff", PERSISTENT},
    {"GithubSshKeys", PERSISTENT | BACKUP},
    {"GithubUsername", PERSISTENT | BACKUP},
    {"GitRemote", PERSISTENT},
    {"GsmApn", PERSISTENT | BACKUP},
    {"GsmMetered", PERSISTENT | BACKUP},
    {"GsmRoaming", PERSISTENT | BACKUP},
    {"HardwareSerial", PERSISTENT},
    {"HasAcceptedTerms", PERSISTENT},
    {"InstallDate", PERSISTENT},
    {"IsDriverViewEnabled", CLEAR_ON_MANAGER_START},
    {"IsEngaged", PERSISTENT},
    {"IsLdwEnabled", PERSISTENT | BACKUP},
    {"IsMetric", PERSISTENT | BACKUP},
    {"IsOffroad", CLEAR_ON_MANAGER_START},
    {"IsOnroad", PERSISTENT},
    {"IsRhdDetected", PERSISTENT},
    {"IsReleaseBranch", CLEAR_ON_MANAGER_START},
    {"IsTakingSnapshot", CLEAR_ON_MANAGER_START},
    {"IsTestedBranch", CLEAR_ON_MANAGER_START},
    {"JoystickDebugMode", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LanguageSetting", PERSISTENT | BACKUP},
    {"LastAthenaPingTime", CLEAR_ON_MANAGER_START},
    {"LastGPSPosition", PERSISTENT},
    {"LastManagerExitReason", CLEAR_ON_MANAGER_START},
    {"LastOffroadStatusPacket", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LastPowerDropDetected", CLEAR_ON_MANAGER_START},
    {"LastUpdateException", CLEAR_ON_MANAGER_START},
    {"LastUpdateTime", PERSISTENT},
    {"LiveDelay", PERSISTENT | BACKUP},
    {"LiveParameters", PERSISTENT},
    {"LiveParametersV2", PERSISTENT},
    {"LiveTorqueParameters", PERSISTENT | DONT_LOG},
    {"LocationFilterInitialState", PERSISTENT},
    {"LongitudinalManeuverMode", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"LongitudinalPersonality", PERSISTENT | BACKUP},
    {"NetworkMetered", PERSISTENT | BACKUP},
    {"ObdMultiplexingChanged", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"ObdMultiplexingEnabled", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_BadNvme", CLEAR_ON_MANAGER_START},
    {"Offroad_CarUnrecognized", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_ConnectivityNeeded", CLEAR_ON_MANAGER_START},
    {"Offroad_ConnectivityNeededPrompt", CLEAR_ON_MANAGER_START},
    {"Offroad_IsTakingSnapshot", CLEAR_ON_MANAGER_START},
    {"Offroad_NeosUpdate", CLEAR_ON_MANAGER_START},
    {"Offroad_NoFirmware", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_Recalibration", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_StorageMissing", CLEAR_ON_MANAGER_START},
    {"Offroad_TemperatureTooHigh", CLEAR_ON_MANAGER_START},
    {"Offroad_UnofficialHardware", CLEAR_ON_MANAGER_START},
    {"Offroad_UpdateFailed", CLEAR_ON_MANAGER_START},
    {"OnroadCycleRequested", CLEAR_ON_MANAGER_START},
    {"OpenpilotEnabledToggle", PERSISTENT | BACKUP},
    {"PandaHeartbeatLost", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"PandaSomResetTriggered", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"PandaSignatures", CLEAR_ON_MANAGER_START},
    {"PrimeType", PERSISTENT},
    {"RecordAudio", PERSISTENT | BACKUP},
    {"RecordFront", PERSISTENT | BACKUP},
    {"RecordFrontLock", PERSISTENT},  // for the internal fleet
    {"SecOCKey", PERSISTENT | DONT_LOG | BACKUP},
    {"RouteCount", PERSISTENT},
    {"SnoozeUpdate", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"SshEnabled", PERSISTENT | BACKUP},
    {"TermsVersion", PERSISTENT},
    {"TrainingVersion", PERSISTENT},
    {"UbloxAvailable", PERSISTENT},
    {"UpdateAvailable", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"UpdateFailedCount", CLEAR_ON_MANAGER_START},
    {"UpdaterAvailableBranches", PERSISTENT},
    {"UpdaterCurrentDescription", CLEAR_ON_MANAGER_START},
    {"UpdaterCurrentReleaseNotes", CLEAR_ON_MANAGER_START},
    {"UpdaterFetchAvailable", CLEAR_ON_MANAGER_START},
    {"UpdaterNewDescription", CLEAR_ON_MANAGER_START},
    {"UpdaterNewReleaseNotes", CLEAR_ON_MANAGER_START},
    {"UpdaterState", CLEAR_ON_MANAGER_START},
    {"UpdaterTargetBranch", CLEAR_ON_MANAGER_START},
    {"UpdaterLastFetchTime", PERSISTENT},
    {"Version", PERSISTENT},

    // --- sunnypilot params --- //
    {"AccelPersonality", PERSISTENT},
    {"ApiCache_DriveStats", PERSISTENT},
    {"AutoLaneChangeBsmDelay", PERSISTENT | BACKUP},
    {"AutoLaneChangeTimer", PERSISTENT | BACKUP},
    {"BlinkerMinLateralControlSpeed", PERSISTENT | BACKUP},
    {"BlinkerPauseLateralControl", PERSISTENT | BACKUP},
    {"Brightness", PERSISTENT | BACKUP},
    {"CarParamsSP", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"CarParamsSPCache", CLEAR_ON_MANAGER_START},
    {"CarParamsSPPersistent", PERSISTENT},
    {"CarPlatformBundle", PERSISTENT | BACKUP},
    {"ChevronInfo", PERSISTENT | BACKUP},
    {"CustomAccIncrementsEnabled", PERSISTENT | BACKUP},
    {"CustomAccLongPressIncrement", PERSISTENT | BACKUP},
    {"CustomAccShortPressIncrement", PERSISTENT | BACKUP},
    {"DeviceBootMode", PERSISTENT | BACKUP},
    {"EnableGithubRunner", PERSISTENT | BACKUP},
    {"InteractivityTimeout", PERSISTENT | BACKUP},
    {"IsDevelopmentBranch", CLEAR_ON_MANAGER_START},
    {"MaxTimeOffroad", PERSISTENT | BACKUP},
    {"ModelRunnerTypeCache", CLEAR_ON_ONROAD_TRANSITION},
    {"OffroadMode", CLEAR_ON_MANAGER_START},
    {"QuickBootToggle", PERSISTENT | BACKUP},
    {"QuietMode", PERSISTENT | BACKUP},
    {"ShowAdvancedControls", PERSISTENT | BACKUP},
    {"VibePersonalityEnabled", PERSISTENT},
    {"VibeAccelPersonalityEnabled", PERSISTENT},
    {"VibeFollowPersonalityEnabled", PERSISTENT},

    // MADS params
    {"Mads", PERSISTENT | BACKUP},
    {"MadsMainCruiseAllowed", PERSISTENT | BACKUP},
    {"MadsSteeringMode", PERSISTENT | BACKUP},
    {"MadsUnifiedEngagementMode", PERSISTENT | BACKUP},

    // Model Manager params
    {"ModelManager_ActiveBundle", PERSISTENT},
    {"ModelManager_ClearCache", CLEAR_ON_MANAGER_START},
    {"ModelManager_DownloadIndex", CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION},
    {"ModelManager_LastSyncTime", CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION},
    {"ModelManager_ModelsCache", PERSISTENT | BACKUP},

    // Neural Network Lateral Control
    {"NeuralNetworkLateralControl", PERSISTENT | BACKUP},

    // sunnylink params
    {"EnableSunnylinkUploader", PERSISTENT | BACKUP},
    {"LastSunnylinkPingTime", CLEAR_ON_MANAGER_START},
    {"SunnylinkCache_Roles", PERSISTENT},
    {"SunnylinkCache_Users", PERSISTENT},
    {"SunnylinkDongleId", PERSISTENT},
    {"SunnylinkdPid", PERSISTENT},
    {"SunnylinkEnabled", PERSISTENT},

    // Backup Manager params
    {"BackupManager_CreateBackup", PERSISTENT},
    {"BackupManager_RestoreVersion", PERSISTENT},

    // sunnypilot car specific params
    {"HyundaiLongitudinalTuning", PERSISTENT | BACKUP},

    {"DynamicExperimentalControl", PERSISTENT | BACKUP},
    {"BlindSpot", PERSISTENT | BACKUP},

    // model panel params
    {"LagdToggle", PERSISTENT | BACKUP},
    {"LagdToggleDesc", PERSISTENT},
    {"LagdToggledelay", PERSISTENT | BACKUP},

    // mapd
    {"MapAdvisorySpeedLimit", CLEAR_ON_ONROAD_TRANSITION},
    {"MapdVersion", PERSISTENT},
    {"MapSpeedLimit", CLEAR_ON_ONROAD_TRANSITION},
    {"NextMapSpeedLimit", CLEAR_ON_ONROAD_TRANSITION},
    {"Offroad_OSMUpdateRequired", CLEAR_ON_MANAGER_START},
    {"OsmDbUpdatesCheck", CLEAR_ON_MANAGER_START},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", PERSISTENT},
    {"OsmDownloadedDate", PERSISTENT},
    {"OSMDownloadLocations", PERSISTENT},
    {"OSMDownloadProgress", CLEAR_ON_MANAGER_START},
    {"OsmLocal", PERSISTENT},
    {"OsmLocationName", PERSISTENT},
    {"OsmLocationTitle", PERSISTENT},
    {"OsmLocationUrl", PERSISTENT},
    {"OsmStateName", PERSISTENT},
    {"OsmStateTitle", PERSISTENT},
    {"OsmWayTest", PERSISTENT},
    {"RoadName", CLEAR_ON_ONROAD_TRANSITION},
};
