name: Build

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for softprops/action-gh-release to create a release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup dependencies
      run: sudo apt-get update && sudo ./tools/ubuntu_setup.sh

    - name: Build openpilot
      run: scons -j$(nproc)

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: ${{ github.ref_name }}sunnypilot release
        draft: false
        prerelease: false
        files: |
          ./openpilot/selfdrive/assets/fonts/Inter*
          ./openpilot/selfdrive/assets/sounds/*
          ./openpilot/selfdrive/assets/images/*
          ./openpilot/selfdrive/assets/offroad/fcc.html
